### ISSUE TITLE
Upload source code for module to support pedigree drawing for OpenMRS 2.0

### ISSUE THREAD

**Issue by surangak** [surangak/HguSriLanka#5]
a) Make sure that the module is well refactored. What name have you given this new module?
b) Please make sure to include a readme file with proper documentation on how to use the module (pre-requisites), compatible versions etc.

**Comment by akshika47** [comment]
I uploaded the module. I will add a read me file.  as well.

Name of the module is hgu. would that collide with some other module?

**Comment by surangak** [comment]
Hmm... names are always hard. Why not call it pedigreedrawing? hgu is not very descriptive of what it really does.
Make sure you stick to naming conventions in https://wiki.openmrs.org/display/docs/Module+Conventions
